### ISSUE TITLE
Blocks links not working properly in the diagram editor

### ISSUE THREAD

**Issue by OscarMrZ** [JdeRobot/bt-studio#185]
When editing the tree with the diagram editor, there seems to be a problem with linking blocks. I can add them normally, but then there's an erratic behavior when trying to connect them. It happens when trying to add a third block to a sequence or similar. From my testing it happens with all blocks, but further testing is needed. 

![example_1](https://github.com/user-attachments/assets/b4bbaf0d-22e3-473d-aeff-e4508978ae4f)

![Untitled design](https://github.com/user-attachments/assets/d78dca8e-cfbd-4f97-86f8-34dbeab59925)

**Comment by javizqh** [comment]
It only happends when adding a node below it. If you try to add the same one above the rest it works properly
