### ISSUE TITLE
Zip files not working

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/bt-studio#191]
All of the zips are not working. In the RAM trying to execute the app the error is: Bad magic number for central directory

**Comment by javizqh** [comment]
The temporary files created by the backend work properly, so the problem has to be in the frontend

**Comment by javizqh** [comment]
The calls from the frontend to the backend that return a zip must be called using fetch, not axios

**Comment by OscarMrZ** [comment]
That's not really the case. The important bit is handling the response as a [blob](https://axios-http.com/docs/req_config#:~:text=//%20%60responseType%60%20indicates%20the%20type%20of%20data%20that%20the%20server%20will%20respond%20with%0A%20%20//%20options%20are%3A%20%27arraybuffer%27%2C%20%27document%27%2C%20%27json%27%2C%20%27text%27%2C%20%27stream%27%0A%20%20//%20%20%20browser%20only%3A%20%27blob%27%0A%20%20responseType%3A%20%27json%27%2C%20//%20default). In #194 you can check the app generation wrapper working with axios.
