### ISSUE TITLE
Web GUI for tree creation. 

### ISSUE THREAD

**Issue by OscarMrZ** [JdeRobot/bt-studio#27]
Currently, the app is generated by writing the XML structure and executing the different generation scripts. The goal of the next version is to develop a web frontend for writing action and tree creation. This opens the door to future integrations with a dockerized ROS 2 environment.

**Comment by sorawit112** [comment]
I have implemented something like the BT factory and I used Groot GUI for generate and write XML then input to by BT.factory to Building PyTree

**Comment by OscarMrZ** [comment]
Hi @sorawit112, thanks for reaching out! Glad to know about your project. If I understand correctly, your code makes possible the use of Groot for coding trees in py_trees. I took a slightly different approach: adapt py_trees to the BT.cpp syntax. In that way, the users can create trees with the BT.cpp nodes, with the same behavior. I have done this for easier portability. The goal of this project is to generate a web-based tree creation tool, but i will research about integrating Groot directly.
