### ISSUE TITLE
Tree editor improvement

### ISSUE THREAD

**Issue by JSA02** [JdeRobot/bt-studio#44]
Really nice project!

However I think there may be a few improvements:
1.- The zoom is really anti-intuitive.
2.- The selected node should be highlighted.
3.- A node should not have two parents.
4.- Baobab could be a great name for this project!!

**Comment by OscarMrZ** [comment]
Hi Juan! 

I totally agree with your suggestions. I'll try to implement this fixes into the next version!

**Comment by javizqh** [comment]
The features suggested in 1, 2 and 3 will be integrated in BT-Studio with the merge of #89

**Comment by javizqh** [comment]
Thanks for your name suggestion but we have decided to continue with BT Studio
