### ISSUE TITLE
starting of the frontend doesnt work

### ISSUE THREAD

**Issue by Guelakais** [JdeRobot/bt-studio#61]
Start the front end with the following code:
```
cd ..
 cd frontend
yarn install
yarn start
```
produced the following error:
```
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'start'
```
Also, I think the installation process is still not very streamlined. I would recommend using a container for development. I asked bard how to add the installation process to a Docker container. Maybe this will help you:
Dockerfile:
```
FROM ros:humble

RUN source /opt/ros/humble/setup.bash

WORKDIR /opt/bt-studio
RUN git clone https://github.com/JdeRobot/bt-studio

RUN sudo apt update && sudo apt install python3-vcstool python3-pip python3-rosdep python3-colcon-common-extensions -y

WORKDIR /opt/bt-studio/backend
RUN pip install virtualenv
RUN virtualenv backend_env
RUN source backend_env/bin/activate
RUN pip install django djangorestframework
https://github.com/Guelakais
CMD python3 manage.py runserver

WORKDIR /opt/bt-studio/frontend
RUN yarn install
RUN yarn start

EXPOSE 3000
```
And now how to start it:
```
docker build -t bt-studio .
docker run -it -p 3000:3000 bt-studio
```
You should find the frontend at `http://localhost:3000`

**Comment by OscarMrZ** [comment]
Hi @Guelakais, thanks for your comments!

Absolutely, I'm aware the project currently does not have the best installation method. I'm working in the integration of the project with a dockerized execution environment as in [RoboticsAcademy](https://github.com/JdeRobot/RoboticsAcademy), so I'll try to streamline the installation the next update. 

Regarding the current installation errors, I'll check it out, maybe I forgot some dependency. Do you have yarn installed in your pc?

**Comment by Maik13579** [comment]
Hey I solved it by adding these lines to my Dockerfile

```
#https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install
RUN apt remove cmdtest \
&& apt remove yarn \
&& curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list \
&& apt-get update \
&& apt-get install yarn -y
```

But I stuck at this error message:

```bash
bt-studio    | Watching for file changes with StatReloader
bt-studio    | yarn run v1.22.19
bt-studio    | $ react-scripts start
bt-studio    | Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
bt-studio    |  - options.allowedHosts[0] should be a non-empty string.
bt-studio    | error Command failed with exit code 1.
bt-studio    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
bt-studio exited with code 1
```

**Comment by Maik13579** [comment]
I solved it by deleting the line '"proxy":  "http://localhost:8000"' from the package.json file

Now it works but when I create a new project I always get the message `The project test already exists`

Thats my Dockerfile
```
ARG BASE_IMAGE=ros:humble
FROM $BASE_IMAGE as base

RUN apt update && apt install -y\
    wget \
    curl \
    python3-vcstool \
    python3-pip \
    python3-rosdep \
    python3-colcon-common-extensions \
&& pip3 install django djangorestframework

#https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install
RUN apt remove cmdtest \
&& apt remove yarn \
&& curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list \
&& apt-get update \
&& apt-get install yarn -y

WORKDIR /root
RUN wget https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-x64.tar.xz \
&& tar -xf node-v20.9.0-linux-x64.tar.xz \
&& rm node-v20.9.0-linux-x64.tar.xz \
&& mv node-v20.9.0-linux-x64 node \
&& rm -rf /usr/bin/node /usr/bin/npm /usr/bin/npx \
&& ln -s /root/node/bin/node /usr/bin/node \
&& ln -s /root/node/bin/npm /usr/bin/npm \
&& ln -s /root/node/bin/npx /usr/bin/npx

ENV WS=/root/ros2_ws/src/prj-iki/barrob/utils/bt-studio
COPY submodules/bt-studio $WS

RUN cd ${WS}/frontend \
#delete line 5 'proxy": "http://localhost:8000"''
&& sed -i '5d' package.json \
&& yarn install

CMD bash -c "python3 ${WS}/backend/manage.py runserver & cd ${WS}/frontend && yarn start"
EXPOSE 3000
```

**Comment by OscarMrZ** [comment]
Hi @Maik13579, I haven't have time yet to work in the dockerized execution. Quite helpful though, thanks! I'll take it into consideration when I implement it. I see you have added instructions for the installation of yarn in the docker. About the error of existing proxy, that's weirder, I'll check the config and let you know.

**Comment by OscarMrZ** [comment]
Hi all!

I have expanded the installation instructions, I forgot to add yarn and nodejs installation instructions. Could u check if you are now able to start the frontend now and let me know?

And @Maik13579, analyzing your problem with more detail, it is probably because the frontend cannot communicate with the backend. I have already change the warning error, because it is very misleading!

I will have a dockerized execution in a few days I hope.

**Comment by OscarMrZ** [comment]
Setting this as close as I cannot replicate the error
