### ISSUE TITLE
shifted figures, buttons don't work (frontend)

### ISSUE THREAD

**Issue by Nazerek** [JdeRobot/bt-studio#77]
Hi! I am a MacOS user and everything executes without error(in both terminals). However, I was trying to write&download some code to test in ROS afterward. But cannot download since I keep getting such display and some buttons are not active. What can be the reason?

<img width="220" alt="Screenshot 2024-04-19 at 18 47 01" src="https://github.com/JdeRobot/bt-studio/assets/26089594/a607545c-5a1a-4cd7-a7ce-835bbdd07fa1">

**Comment by Nazerek** [comment]
zoomed out the screen and I could download the file but buttons from the top are still shifted.  Looks like there is some version conflict with my setup
<img width="250" alt="Screenshot 2024-04-19 at 19 03 43" src="https://github.com/JdeRobot/bt-studio/assets/26089594/769bdb89-8ccd-4a59-a48b-06cb12eebf2d">
.

**Comment by OscarMrZ** [comment]
Hi! This seems to be an issue in the chrome-based browser. Please try using BT Studio in firefox for the moment. We'll try to fix it in the future.

**Comment by javizqh** [comment]
Yes. I think it seems to be the exact same one as in #71

**Comment by Nazerek** [comment]
oh I see, thanks
