### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by M-Rahul1** [JdeRobot/bt-studio#80]
how does creating new actions, for example turn.py create a new node in your frontend.
What is the logic behind your node creation for action nodes.
![image](https://github.com/JdeRobot/bt-studio/assets/68385075/d48d848a-6a2d-46de-ade7-1293fdbf7e3d)

**Comment by javizqh** [comment]
Right now it is done by reading the name of the files created. For example if the file is named TurnAction, it will be added with the same name, it does not care for the class name, but you must name the class with the same name as the file.

The code corresponding to the update of the nodes in the frontend can be found in [here](https://github.com/JdeRobot/bt-studio/blob/main/frontend/src/components/diagram_editor/NodeHeader.js#L45).

Hope you find this useful.
