### ISSUE TITLE
Upgrades before going online

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/bt-studio#93]
This is a list of all of changes that will be done to BT Studio before the merge is done.

- [X] #94
- [X] #95
- [X] #96
- [x] #107
- [X] New dialog window for creating new files
- [X] #97
- [x] #104
- [X] #98
- [X] When creating a file always en with .py
- [x] #102
- [X] #99
- [X] #100
- [x] #105
- [ ] BT sort button
- [x] #103
- [X] #101
- [ ] Horizontal Bt (Maybe)
- [ ] Add toggle between horizontal bt and vertical (Maybe)
- [ ] Solving the Tab inconsistency from ACE
- [x] #106

**Comment by OscarMrZ** [comment]
I think almost everything from this list is completed. @javizqh is it ok with you to close this big issue and work in a separate one for each issue?

**Comment by javizqh** [comment]
Yes, this can be closed without a problem
